name: Sample workflow for App Center action
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@master
      - name: Get sample .apk for test purposes
        run: wget https://github.com/appium/appium/raw/master/sample-code/apps/ApiDemos-debug.apk
      - name: Upload artefact to AppCenter  
        uses: ./
        with:
          appName: ${{secrets.APP_NAME}} 
          token: ${{secrets.API_TOKEN}} 
          group: Collaborators 
          file: ApiDemos-debug.apk 
