name: Sample workflow for App Center action
on: [push, pull_request, workflow_dispatch, pull_request_target]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get sample .apk for test purposes
        run: wget --output-document ApiDemos-debug.apk https://github.com/appium/appium/blob/906350fd335f9485376214fdd17c7cdb6c9ff26b/sample-code/apps/ApiDemos-debug.apk?raw=true
      - name: Upload artifact with provided release notes
        uses: ./
        with:
          appName: ${{secrets.ANDROID_APP_NAME}}
          token: ${{secrets.API_TOKEN}}
          group: Collaborators
          file: ApiDemos-debug.apk
          releaseNotes: New bugs
      - name: Upload artifact with empty release notes
        uses: ./
        with:
          appName: ${{secrets.ANDROID_APP_NAME}}
          token: ${{secrets.API_TOKEN}}
          group: Collaborators
          file: ApiDemos-debug.apk
      - name: Upload artifact with Git generated release notes
        uses: ./
        with:
          appName: ${{secrets.ANDROID_APP_NAME}}
          token: ${{secrets.API_TOKEN}}
          group: Collaborators
          file: ApiDemos-debug.apk
          gitReleaseNotes: true
      - name: Upload artifact and notify testers
        uses: ./
        with:
          appName: ${{secrets.ANDROID_APP_NAME}}
          token: ${{secrets.API_TOKEN}}
          group: Collaborators
          file: ApiDemos-debug.apk
          notifyTesters: true
      - name: Upload artifact with a debug flag
        uses: ./
        with:
          appName: ${{secrets.ANDROID_APP_NAME}}
          token: ${{secrets.API_TOKEN}}
          group: Collaborators
          file: ApiDemos-debug.apk
          debug: true

